---
output:
  pdf_document: default
subparagraph: yes
header-includes: |
  \input{workshops.tex}
  \geometry{letterpaper, portrait, margin=.5in}
  \usepackage{titlesec}
  \titlespacing{\section}{0pt}{0pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
  \titlespacing{\subsection}{0pt}{0pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
  \titlespacing{\subsubsection}{0pt}{0pt plus 2pt minus 1pt}{0pt plus 1pt minus 1pt}
---

<!-- describes the design of your workshop -->

<!-- An itinerary / timeline of what is taught and what methods are used -->
<!-- A description of the audience and any techniques you might use to discover their strengths and weaknesses more fully -->
<!-- Goals of the workshop -->
<!-- Expectations / community agreements / code of conduct you would offer to learners -->
<!-- Challenges you foresee and possible ways to address them -->
<!-- Potential ways to differentiate learning for learners who are struggling with the content or are bored because they are ahead of others -->
<!-- Proposed methods to measure the success of the workshop -->
<!-- Formative or summative assessments -->
<!-- A mind map / concept map of the topics you’re covering -->

# Intro to Linear Models in R: From Data to Manuscript

### Audience

This workshop is geared toward people working on practical data analysis problems in a research context. 
To that end, the example data is from a research project (the ATLAS study on steroid use in adolescent athletes),
and the final product of the analysis document is assumed to be a manuscript for submission to a scientific journal.
It is appropriate for beginners, but learners should have at least some exposure to R (or be willing to jump in quickly) and some basic stats training.
<!-- In terms of R experience, someone who had attended an intro to R workshop but wasn't really up to using R on their own yet should be able to follow along just fine. In terms of stats experience, this workshop would be best for people that have run linear models before or at least know what they are but are looking for help doing that kind of analysis in R. -->

This workshop scales well from small groups to 50+. 
<!-- When I gave a version of this workshop at the University of Oregon, I had an audience of 45, consisting of mostly grad students and postdocs, as well as several PIs and a handful of exceptional undergrads.  -->

### Learning Objectives:

- understand the difference (in R) between estimating a linear model and presenting the results
<!-- One of my many favorite things about R is that it draws a clear distinction between estimating the model and presenting the results, unlike many other statistical environments. I think that's definitely the most coherent approach, but it can be a stumbling block for folks who are used to working with software that conflates estimation and presentation, like SPSS, so I make sure to spend a little time on it. -->
- be able to understand and write model formulas for the `lm()` function
<!-- in my experience, this is one of the first stumbling blocks for folks getting started with ilnear models in R, so I devote a fair amount of time to exploring how formulas work and giving people practice with them so they can go home and write forumlas for their own data analysis questions. -->
<!-- This is the part of the workshop that I chose for the demonstration, so you'll be able to see this material in action. -->
- understand and execute code for a start-to-finish regression analysis, including bringing the data into R, estimating the model, and exploring the results via table output and plots
- be able to identify some advantages of literate statistical programming over more traditional analysis practices
- be able to write a minimal example of a scientific manuscript in R-markdown featuring a regression analysis and output 
<!-- As I menioned, I do assume some stats training, so the way the workshop is written now I don't spend time expaining what linear models are, beyond a quick overview. Things I'm glossing over include: study design, violations to the assumptions of the linear model (e.g. non-normal residuals, clustered data), strategies for handling outliers and missing data, ins and outs of hypothesis testing and interpretation, etc. -->

### Workshop Outline: 

- Background and overview
- Running linear models
     - Prepping the data
     - Writing the model formula
     - Running the model
- Presenting model results
     - Literate statistical programming
     - Summarizing the results
     - Plotting
- Data to manuscript
     - Your R-markdown document
     - Table output
     - In-line stats
     - Perfecting plots
     - Writing and citations

### Teaching Philosophy


*Universal Design:* Teaching materials should be designed to be accessible to a wide range of learners from the get go, rather than planing to make accommodations in response to expressed need. 
<!-- diverse learners might include thsoe with dyslexia, attention disorders, vision or hearing impariment, language barriers, limited access to expensive tech, not having had coffee yet, etc. -->
<!-- This is an improatnt equity consideration in terms of making content accessible for folks who might not otherwise be able to learn from it, but it actually helps all learners. -->
Some ways I incorporate universal design in my workshops include:

- set clear expectations at the beginning and offer suggestions for how best to make use of the workshop
<!-- I actually go over most of the material we're talking about at the beginning of a workshop, not quite to this level of detail -->
- information consistently communicated over multiple modalities (e.g. double up visual and auditory)
- simple, uncluttered design and file formats that work on any operating system
<!-- makes it easier for folks using accessibility software like text to speech or translation -->
- slide numbers on every slide, and slide deck available along with data and code

<!-- Folks often know how best to set themselves up for success, and they'll do it fi you just provide the flexibility to accommodate a range of styles. If you guve them the tools, they'll do whatever works best for them, which is perfect. -->

*Practical Considerations:* I encourage learners to follow along and run code themselves, either in their own R Studio, or at rstudio.cloud.
The best way to learn R is by using R!
For those of you who are R folks: I steer learners toward the R Studio environment, `tidyverse` packages, and R-markdown, using the `rticles` package for creating manuscripts.

For those of you who are cognitive science geeks: 

- interleaved training and progressive alignment
<!-- I'm trying to maximize learners' ability to generalize what they learn here to new circumstances -->
- realistic practice problems from the two perspectives learners are most likely to encounter in real life
<!-- I have an idea in my head and I need to turn it into code, and I've got some code here and I need to figure out what it does. -->
- consistent color-coding of different types of information
<!--  throughout to help learners allocate their attention in support of their learning goals, and to facilitate appropriate comparison across situations. -->

\hwydt{ }
\wwtd{ }
\learnmore{resources to check out}
\keyidea{the big ideas you need to hold on to}
\seealso{other functions or packages that do a similar thing}

<!-- These boxes also help learners adapt the workshop to their level/needs: Folks who have more experience or need more of a challenge can pursue the seealso options and expand practical examples from hwydt and wwtd to try out more scenarios or bring workshop examples closer to their own data analysis. People who are struggling can circle back to the learnmore resources for additional context and practice. -->
